import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import Weather from "../components/Weather";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
    });
    setCity("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div className="container">
        <Head>
          <title>Weather - Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="block-meteo">
          <form onSubmit={fetchWeather} className="form-meteo">
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className="input-city"
                type="text"
                placeholder="Search city"
              />
            </div>
            <button onClick={fetchWeather}></button>
          </form>
          {weather.main && <Weather data={weather} />}
        </main>
      </div>
    );
  }
}
